from solution import *


def test_load_input() -> None:
    expected: Input = [
        (
            [
                frozenset("be"),
                frozenset("cfbegad"),
                frozenset("cbdgef"),
                frozenset("fgaecd"),
                frozenset("cgeb"),
                frozenset("fdcge"),
                frozenset("agebfd"),
                frozenset("fecdb"),
                frozenset("fabcd"),
                frozenset("edb"),
            ],
            [
                frozenset("fdgacbe"),
                frozenset("cefdb"),
                frozenset("cefbgd"),
                frozenset("gcbe"),
            ],
        ),
        (
            [
                frozenset("edbfga"),
                frozenset("begcd"),
                frozenset("cbg"),
                frozenset("gc"),
                frozenset("gcadebf"),
                frozenset("fbgde"),
                frozenset("acbgfd"),
                frozenset("abcde"),
                frozenset("gfcbed"),
                frozenset("gfec"),
            ],
            [
                frozenset("fcgedb"),
                frozenset("cgb"),
                frozenset("dgebacf"),
                frozenset("gc"),
            ],
        ),
        (
            [
                frozenset("fgaebd"),
                frozenset("cg"),
                frozenset("bdaec"),
                frozenset("gdafb"),
                frozenset("agbcfd"),
                frozenset("gdcbef"),
                frozenset("bgcad"),
                frozenset("gfac"),
                frozenset("gcb"),
                frozenset("cdgabef"),
            ],
            [frozenset("cg"), frozenset("cg"), frozenset("fdcagb"), frozenset("cbg")],
        ),
        (
            [
                frozenset("fbegcd"),
                frozenset("cbd"),
                frozenset("adcefb"),
                frozenset("dageb"),
                frozenset("afcb"),
                frozenset("bc"),
                frozenset("aefdc"),
                frozenset("ecdab"),
                frozenset("fgdeca"),
                frozenset("fcdbega"),
            ],
            [
                frozenset("efabcd"),
                frozenset("cedba"),
                frozenset("gadfec"),
                frozenset("cb"),
            ],
        ),
        (
            [
                frozenset("aecbfdg"),
                frozenset("fbg"),
                frozenset("gf"),
                frozenset("bafeg"),
                frozenset("dbefa"),
                frozenset("fcge"),
                frozenset("gcbea"),
                frozenset("fcaegb"),
                frozenset("dgceab"),
                frozenset("fcbdga"),
            ],
            [
                frozenset("gecf"),
                frozenset("egdcabf"),
                frozenset("bgf"),
                frozenset("bfgea"),
            ],
        ),
        (
            [
                frozenset("fgeab"),
                frozenset("ca"),
                frozenset("afcebg"),
                frozenset("bdacfeg"),
                frozenset("cfaedg"),
                frozenset("gcfdb"),
                frozenset("baec"),
                frozenset("bfadeg"),
                frozenset("bafgc"),
                frozenset("acf"),
            ],
            [
                frozenset("gebdcfa"),
                frozenset("ecba"),
                frozenset("ca"),
                frozenset("fadegcb"),
            ],
        ),
        (
            [
                frozenset("dbcfg"),
                frozenset("fgd"),
                frozenset("bdegcaf"),
                frozenset("fgec"),
                frozenset("aegbdf"),
                frozenset("ecdfab"),
                frozenset("fbedc"),
                frozenset("dacgb"),
                frozenset("gdcebf"),
                frozenset("gf"),
            ],
            [
                frozenset("cefg"),
                frozenset("dcbef"),
                frozenset("fcge"),
                frozenset("gbcadfe"),
            ],
        ),
        (
            [
                frozenset("bdfegc"),
                frozenset("cbegaf"),
                frozenset("gecbf"),
                frozenset("dfcage"),
                frozenset("bdacg"),
                frozenset("ed"),
                frozenset("bedf"),
                frozenset("ced"),
                frozenset("adcbefg"),
                frozenset("gebcd"),
            ],
            [
                frozenset("ed"),
                frozenset("bcgafe"),
                frozenset("cdgba"),
                frozenset("cbgef"),
            ],
        ),
        (
            [
                frozenset("egadfb"),
                frozenset("cdbfeg"),
                frozenset("cegd"),
                frozenset("fecab"),
                frozenset("cgb"),
                frozenset("gbdefca"),
                frozenset("cg"),
                frozenset("fgcdab"),
                frozenset("egfdb"),
                frozenset("bfceg"),
            ],
            [frozenset("gbdfcae"), frozenset("bgc"), frozenset("cg"), frozenset("cgb")],
        ),
        (
            [
                frozenset("gcafb"),
                frozenset("gcf"),
                frozenset("dcaebfg"),
                frozenset("ecagb"),
                frozenset("gf"),
                frozenset("abcdeg"),
                frozenset("gaef"),
                frozenset("cafbge"),
                frozenset("fdbac"),
                frozenset("fegbdc"),
            ],
            [
                frozenset("fgae"),
                frozenset("cfgab"),
                frozenset("fg"),
                frozenset("bagce"),
            ],
        ),
    ]
    assert load_input() == expected


def test_part1() -> None:
    expected: int = 26
    assert part1(load_input()) == expected


def test_part2() -> None:
    expected: int = 61229
    assert part2(load_input()) == expected
